<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sVTS Cat CMS%s'), '<span class="zf-green">', '</span>') ?></h1>
    
</div>
<?php echo $this->a ?>
<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Multi Layout') ?></h2>
        <p><?php echo $this->translate('You can use multi layout for your system. To access to layout and themes library to download or install them to your system. Click here to choose theme and layout.') ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Explore Template') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Many Modules') ?></h2>
        <p><?php echo $this->translate('You will have many modules support for your business. You access to module market to download and setup system.') ?></p>
        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore Modules') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p><?php echo $this->translate('We support you by email when you use our system. Support include: setup, bug, update data... If you need some module to use for your business, you contact with we. We will build to you.') ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Support System') ?> &raquo;</a></p>
   </div>
</div>
